# Vagrantfile for Ubuntu 24.04 x64 Desktop VMware VM

description = "Ubuntu-Desktop-24"

Vagrant.configure("2") do |config|

  # Common box configuration
  config.vm.box = "ubuntu-24.04-x64-desktop-template-vmware"
  config.vm.box_url = "file://#{File.expand_path("output/ubuntu-24.04-x64-desktop-template-vmware.box", __dir__)}"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # -------------------------
  # Shared VMware settings
  # VMX settings can be set here if needed
  # -------------------------
  config.vm.provider "vmware_desktop" do |v|
    v.gui                            = true
    v.vmx["ethernet0.connectionType"] = "nat"
    v.vmx["ethernet0.present"]        = "TRUE"
    v.vmx["hgfs.linkrootshare"]       = "FALSE"
    v.vmx["hgfs.maprootshare"]        = "FALSE"
    v.vmx["isolation.tools.hgfs.disable"] = "TRUE"
    v.vmx["memsize"]                  = "16384" # 16 GB RAM
    v.vmx["numvcpus"]                 = "4"
    v.vmx["sound.autodetect"]         = "TRUE"
    v.vmx["sound.present"]            = "TRUE"
    v.vmx["sound.startConnected"]     = "TRUE"
    v.vmx["vhv.enable"]               = "TRUE" # Enable nested virtualization
  end

  # -------------------------
  # Base VM (NO provisioning)
  # -------------------------
  config.vm.define "base" do |base|
    base.vm.hostname = "ub24-base"
    base.ssh.username = "syselement"
    base.ssh.password = "packer"
    base.ssh.keep_alive = true
    base.ssh.connect_timeout = 30
    base.ssh.insert_key = false

    base.vm.provider "vmware_desktop" do |v|
      v.vmx["displayname"] = "#{description}-Base"
    end
  end

  # ---------------------------------
  # Provisioned VM
  # ---------------------------------
  config.vm.define "provisioned" do |prov|
    prov.vm.hostname = "ub24-desktop"
    prov.ssh.username = "syselement"
    prov.ssh.password = "packer"
    prov.ssh.keep_alive = true
    prov.ssh.connect_timeout = 30
    prov.ssh.insert_key = false

    prov.vm.provider "vmware_desktop" do |v|
      v.vmx["displayname"] = "#{description}"
    end

    prov.vm.provision "shell",
      path: "scripts/02-provision-system.sh",
      privileged: true,
      run: "once"

    prov.vm.provision "shell",
      path: "scripts/03-customize-system.sh",
      privileged: true,
      #run: "never"
      run: "once"
  end

end