# Vagrantfile for Ubuntu 24.04 x64 Desktop VMware VM

description = "Ubuntu-Desktop-24"

Vagrant.configure("2") do |config|
  # Configure the Vagrant box
  config.vm.box              = "ubuntu-24.04-x64-desktop-template-vmware"
  config.vm.box_url = "file://#{File.expand_path("output/ubuntu-24.04-x64-desktop-template-vmware.box", __dir__)}"
  config.vm.hostname         = "ubuntu24-desktop"
  config.ssh.username        = "syselement"
  config.ssh.password        = "packer"
  config.ssh.keep_alive      = true
  config.ssh.connect_timeout = 30
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # VMware provider settings
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    #  VMX settings can be set here if needed
    v.vmx["displayname"]                  = description
    v.vmx["ethernet0.connectionType"]     = "nat"
    v.vmx["ethernet0.present"]            = "TRUE"
    v.vmx["hgfs.linkrootshare"]           = "FALSE"
    v.vmx["hgfs.maprootshare"]            = "FALSE"
    v.vmx["isolation.tools.hgfs.disable"] = "TRUE"
    v.vmx["memsize"]                      = "8192"
    v.vmx["numvcpus"]                     = "4"
    v.vmx["sound.autodetect"]             = "TRUE"
    v.vmx["sound.present"]                = "TRUE"
    v.vmx["sound.startConnected"]         = "TRUE"
    v.vmx["tools.syncTime"]               = "TRUE"
    v.vmx["vhv.enable"]                   = "TRUE" # Enable nested virtualization
  end
end
