#!/usr/bin/env bash
#
# Embed the first-boot stub and its systemd unit into every cloud-init seed
# that asks for them, and check that the embedded copies have not drifted.
#
# cloud-init has no include directive: write_files content must be inline. So
# the files in scripts/ubuntu/firstboot/ are the single source, this copies
# them in, and --check fails a build when a copy no longer matches. Without
# that, an edit to the stub silently reaches only the seeds someone remembered.
#
# A seed opts in by carrying the two marker lines; everything between them is
# regenerated and must not be edited by hand.
#
# Docs:
#   cloud-init  https://cloudinit.readthedocs.io/en/latest/reference/modules.html#write-files
#   README.md   the first-boot runner and its settings
#
# Run:
#   scripts/sync-firstboot.sh            # rewrite the embedded copies
#   scripts/sync-firstboot.sh --check    # fail if any copy has drifted

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
readonly FIRSTBOOT_DIR="$REPO_ROOT/scripts/ubuntu/firstboot"

readonly BEGIN_MARKER='# >>> packertron-firstboot: generated by scripts/sync-firstboot.sh >>>'
readonly END_MARKER='# <<< packertron-firstboot <<<'

CHECK_ONLY=false
drifted=0

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

# Indent without touching empty lines: padding them would leave trailing
# whitespace, which `git diff --check` rejects.
indent_content() {
    awk -v pad="          " '{ if (length($0)) print pad $0; else print "" }' "$1"
}

emit_entry() {
    local path="$1" mode="$2" source_file="$3"

    printf '      - path: %s\n' "$path"
    printf '        owner: root:root\n'
    printf "        permissions: '%s'\n" "$mode"
    printf '        content: |\n'
    indent_content "$source_file"
}

generated_block() {
    printf '      %s\n' "$BEGIN_MARKER"
    emit_entry /usr/local/sbin/packertron-firstboot 0750 "$FIRSTBOOT_DIR/stub.sh"
    emit_entry /etc/systemd/system/packertron-firstboot.service 0644 \
        "$FIRSTBOOT_DIR/packertron-firstboot.service"
    printf '      %s\n' "$END_MARKER"
}

seed_files() {
    grep -rl -- "$BEGIN_MARKER" \
        "$REPO_ROOT/scripts/ubuntu" \
        "$REPO_ROOT/templates" \
        "$REPO_ROOT/deploy" 2>/dev/null | sort -u
}

# awk rather than sed: the replacement is multi-line and contains every
# character sed would treat as special.
#
# The values arrive through the environment rather than -v, which expands
# escape sequences in what it is given: -v silently turned every \" and \$ in
# the embedded stub into a bare quote or dollar, committing corrupted Bash to
# the seed.
render_seed() {
    local seed="$1"

    AWK_BLOCK="$2" AWK_BEGIN="$BEGIN_MARKER" AWK_END="$END_MARKER" awk '
        BEGIN {
            block = ENVIRON["AWK_BLOCK"]
            begin = ENVIRON["AWK_BEGIN"]
            end   = ENVIRON["AWK_END"]
        }
        index($0, begin) { print block; skipping = 1; next }
        index($0, end)   { skipping = 0; next }
        !skipping        { print }
    ' "$seed"
}

process_seed() {
    local seed="$1" block rendered relative
    relative="${seed#"$REPO_ROOT"/}"

    block="$(generated_block)"
    rendered="$(render_seed "$seed" "$block")"

    if [[ "$rendered" == "$(cat "$seed")" ]]; then
        printf '   ok    %s\n' "$relative"
        return
    fi

    if [[ "$CHECK_ONLY" == true ]]; then
        printf '   DRIFT %s: embedded first-boot files differ from scripts/ubuntu/firstboot/\n' \
            "$relative" >&2
        drifted=$((drifted + 1))
        return
    fi

    printf '%s\n' "$rendered" >"$seed"
    printf '   sync  %s\n' "$relative"
}

main() {
    local seed found=0

    [[ "${1:-}" != --check ]] || CHECK_ONLY=true
    [[ -d "$FIRSTBOOT_DIR" ]] || die "missing ${FIRSTBOOT_DIR}"

    while read -r seed; do
        [[ -n "$seed" ]] || continue
        found=$((found + 1))
        process_seed "$seed"
    done < <(seed_files)

    ((found > 0)) || die "no seed carries the first-boot marker"

    if ((drifted > 0)); then
        printf '\n%d seed(s) out of date; run scripts/sync-firstboot.sh\n' "$drifted" >&2
        exit 1
    fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
