# This is a basic workflow to help you get started with Actions

name: Changelog CI

# Controls when the workflow will run
on:
  release:
    types: [created, edited]
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "✏️ Conventional Changelog Action"
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          skip-git-pull: "true"
